spring:
  application:
    name: AiChat
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.232.170.147:3306/aichat
    username: root
    password: 2771651667
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600
      database: 0
server:
  port: 8123
  servlet:
    context-path: /api
    # springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.character.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
    # AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: sk-db75053af740430794b8909f1f9fb4cf
      model-name: qwen-plus-2025-07-28
      log-requests: true
      log-responses: true
      max-tokens: 8192
    text-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: sk-db75053af740430794b8909f1f9fb4cf
      model-name: text-embedding-v4
      log-requests: true
      log-responses: true
      max-tokens: 8192


# 日志配置
# 日志配置
logging:
  level:
    com.character: DEBUG
    org.java_websocket: INFO
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"