server:
  port: 8123

spring:
  application:
    name: ai-character-play
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
# 讯飞语音识别配置
xunfei:
  app-id: 0cf43f30
  access-key-id: f22002ae080385f704032f9d53fb9d45
  access-key-secret: M2NkMGM2NjIzNmIwMGZmNWE5ZDM2YzVh

# 日志配置
logging:
  level:
    com.character: DEBUG
    org.java_websocket: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"